import { GameTTSConfig } from "./index";
import { ObjectMap, Result } from "nodecg-io-core";
export declare class GameTTSClient {
    private readonly config;
    constructor(config: GameTTSConfig);
    private buildBaseURL;
    private executeRequest;
    /**
     * Get all the ids of all voices that gametts supports with a voice name as the object key.
     */
    getVoices(): ObjectMap<number>;
    /**
     * Generates a URL to a .wav file with the spoken text that is generated using GameTTS:
     */
    generateWavUrl(text: string, voiceId: number): string;
    /**
     * Downloads the .wav file from the given URL and returns it as a Buffer.
     * @param url the url generated by {@link generateWavUrl}
     * @returns the wav file
     */
    getWavData(url: string): Promise<ArrayBuffer>;
    isGameTTSAvailable(): Promise<Result<void>>;
}
//# sourceMappingURL=gameTtsClient.d.ts.map