export declare const voiceMap: {
    maleslycynical: string;
    GUSLAR: string;
    orc_boss_clear: string;
    BECCA: string;
    Lorenzo: string;
    "Dieter Gring": string;
    maleeventoned: string;
    Santiago: string;
    "Hans-J\u00F6rg Karrenbrock": string;
    maleuniquegalmar: string;
    maleeventonedaccented: string;
    "Johannes Steck": string;
    Luis: string;
    Delgado: string;
    malenord: string;
    femalecondescending: string;
    YENNEFER: string;
    maleuniquetullius: string;
    "Pit Kr\u00FCger": string;
    Abrax: string;
    Belschwur: string;
    malecommoner: string;
    "Peter Heusch": string;
    maleuniqueulfric: string;
    malecondescending: string;
    Enzo: string;
    "Renier Baaken": string;
    Olf: string;
    Sam: string;
    maleorc: string;
    orc_warrior_dumb: string;
    "Aart Veder": string;
    femalecoward: string;
    maledarkelf: string;
    "Roy Fromlovitz": string;
    maleyoungeager: string;
    "VERDEN PEASANT 03": string;
    femaleuniquedelphine: string;
    AVALLACH: string;
    "Christian Wewerka": string;
    "Frank Ciazynski": string;
    BARON: string;
    "Uwe Koschel": string;
    LAMBERT: string;
    "Christian Jungwirth": string;
    "ZOLTAN CHIVAY": string;
    maleoldkindly: string;
    dlc2maleuniqueneloth: string;
    maleuniquehadvar: string;
    "Michael Lucke": string;
    "Gero Wachholz": string;
    "Achim Barrenstein": string;
    "Christian Schult": string;
    VESEMIR: string;
    femaleorc: string;
    "Helge Heynold": string;
    "Nora Jokhosha": string;
    femaleargonian: string;
    Hernandez: string;
    "Nick Benjamin": string;
    malenordcommander: string;
    femalechild: string;
    malecommoneraccented: string;
    "Nina Hecklau-Denker": string;
    "Andreas Gr\u00F6ber": string;
    TRISS: string;
    "Michael Deckner": string;
    Patty: string;
    Ogre: string;
    femaleeventoned: string;
    maleguard: string;
    "NOVIGRAD RICH MAN 01": string;
    "Helmut Winkelmann": string;
    "Peter Knorr": string;
    ESKEL: string;
    "Helmut Potthoff": string;
    DIJKSTRA: string;
    orc_old_calm: string;
    GERALT: string;
    CIRILLA: string;
    malechild: string;
    malecoward: string;
    femaleoldgrumpy: string;
    femalesultry: string;
    maleuniquebrynjolf: string;
    femalecommoner: string;
    "J\u00FCrgen Christoph Kamcke": string;
    femalecommander: string;
    "Bert Franzke": string;
    Brogar: string;
    "Eugen Tambosi": string;
    "Bert Stevens": string;
    Rachel: string;
    femaleyoungeager: string;
    femaledarkelf: string;
    "Regine Vergeen": string;
    malebrute: string;
    "Karl-J\u00FCrgen Sihler": string;
    orc_old_insidious: string;
    femaleelfhaughty: string;
    femaleshrill: string;
    orc_boss_hard: string;
    Sara: string;
    Leto: string;
    Romanov: string;
    malesoldier: string;
    "Kurt Spielmann": string;
    dlc2maledarkelfcynical: string;
    maleelfhaughty: string;
    "Klaus Bauer": string;
    "KEIRA METZ": string;
    Ash: string;
    HJALMAR: string;
    Danny: string;
    maleoldgrumpy: string;
    "Bodo Henkel": string;
    "Wolff von Lindenau": string;
    "Joachim P\u00FCtz": string;
    malekhajiit: string;
    "Rolf Birkholz": string;
    Carlos: string;
    malecommander: string;
    "Michael Betz": string;
    dlc1seranavoice: string;
    DANDELION: string;
    femalenord: string;
    femaleoldkindly: string;
    Inquisitor: string;
    Player: string;
    "Sabine Fischer": string;
    "Sascha Rotermund": string;
    "Peter Wenke": string;
    maledrunk: string;
};
//# sourceMappingURL=voiceMap.d.ts.map