"use strict";
/**
 * This file was automatically generated by json-schema-to-typescript
 * using the schema at https://docs.streamelements.com/docs/connecting-via-websocket.
 */
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=StreamElementsEvent.js.map